# Generated by Django 3.0.3 on 2020-02-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.TextField()),
                ('prodPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prodCost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prodCreated', models.DateTimeField()),
            ],
        ),
    ]
