# Generated by Django 3.0.3 on 2020-02-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200228_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodName',
        ),
    ]
