# Generated by Django 3.0.3 on 2020-02-28 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_prodname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodDesc',
            field=models.TextField(blank=True, default='No description', null=True, verbose_name='Product Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='prodName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Product'),
            preserve_default=False,
        ),
    ]
