# Generated by Django 3.0.3 on 2020-02-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('product', '0006_auto_20200228_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='prodCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodDesc',
            field=models.TextField(verbose_name='Product Description'),
        ),
    ]
