# Generated by Django 3.0.3 on 2020-02-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200228_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodImage',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image'),
        ),
    ]
