# Generated by Django 3.0.3 on 2020-03-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_prodimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodSlug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
