# Generated by Django 3.0.3 on 2020-03-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_prodoldprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodIsBestseller',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prodIsLimited',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prodIsNew',
            field=models.BooleanField(default=True),
        ),
    ]
