# Generated by Django 3.0.3 on 2020-03-04 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('product', '0011_auto_20200301_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodDesc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodIsBestseller',
            field=models.BooleanField(default=True, verbose_name='Bestseller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodIsLimited',
            field=models.BooleanField(default=True, verbose_name='Limited'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodIsNew',
            field=models.BooleanField(default=True, verbose_name='New'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodName',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodSlug',
            field=models.SlugField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
